"""
Rule-based morphological inflection engine.

Provides verb conjugation, adjective inflection, and noun gender detection
using explicit suffix rules + curated irregular overrides.

Design: regular forms are generated by rules (covers unlimited vocabulary),
irregular forms are looked up in curated tables (covers the ~20-30 most common
irregulars per language). This avoids both opaque ML models and the brittleness
of purely manual dictionaries.
"""

from typing import Optional
from ..parser.enums import SubType


# ============================================================================
# Verb conjugation: irregulars + stem-changers + regular suffix rules
# ============================================================================

# -- Spanish irregular verbs (fully irregular present indicative) --
_ES_IRREGULAR_VERBS = {
    'ser': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'soy',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'eres',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'es',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'somos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'son',
    },
    'ir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'voy',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vas',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'va',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vamos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'van',
    },
    'dar': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'doy',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'das',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'da',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'damos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'dan',
    },
    'haber': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'he',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'has',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'ha',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'hemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'han',
    },
    'hacer': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'hago',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'haces',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'hace',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'hacemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'hacen',
    },
    'decir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'digo',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'dices',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'dice',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'decimos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'dicen',
    },
    'ver': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'veo',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'ves',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 've',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'ven',
    },
    'saber': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'sé',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'sabes',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'sabe',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'sabemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'saben',
    },
}

# Spanish stem-changing verbs: {lemma: (from_vowel, to_vowel)}
# Boot pattern: changes in 1s, 2s, 3s, 3p — NOT in 1p
_ES_STEM_CHANGERS = {
    # e -> ie
    'pensar': ('e', 'ie'), 'cerrar': ('e', 'ie'), 'querer': ('e', 'ie'),
    'tener': ('e', 'ie'), 'venir': ('e', 'ie'), 'entender': ('e', 'ie'),
    'perder': ('e', 'ie'), 'sentir': ('e', 'ie'), 'preferir': ('e', 'ie'),
    'comenzar': ('e', 'ie'), 'empezar': ('e', 'ie'),
    # o -> ue
    'dormir': ('o', 'ue'), 'encontrar': ('o', 'ue'), 'poder': ('o', 'ue'),
    'volver': ('o', 'ue'), 'contar': ('o', 'ue'), 'morir': ('o', 'ue'),
    'recordar': ('o', 'ue'), 'almorzar': ('o', 'ue'), 'mover': ('o', 'ue'),
    # u -> ue
    'jugar': ('u', 'ue'),
    # e -> i
    'perseguir': ('e', 'i'), 'pedir': ('e', 'i'), 'seguir': ('e', 'i'),
    'repetir': ('e', 'i'), 'servir': ('e', 'i'), 'vestir': ('e', 'i'),
}

# Tener/venir also have 1s irregularity (tengo/vengo)
_ES_STEM_CHANGE_1S = {
    'tener': 'tengo', 'venir': 'vengo', 'poner': 'pongo',
    'salir': 'salgo',
}

# -- French irregular verbs --
_FR_IRREGULAR_VERBS = {
    'être': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'suis',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'est',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'sommes',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'sont',
    },
    'avoir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'ai',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'as',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'a',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'avons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'ont',
    },
    'aller': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'vais',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vas',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'va',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'allons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'vont',
    },
    'faire': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'fais',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'fais',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'fait',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'faisons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'font',
    },
    'voir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'vois',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vois',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'voit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'voyons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'voient',
    },
    'vouloir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'veux',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'veux',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'veut',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'voulons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'veulent',
    },
    'savoir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'sais',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'sais',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'sait',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'savons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'savent',
    },
    'pouvoir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'peux',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'peux',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'peut',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'pouvons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'peuvent',
    },
    'venir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'viens',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'viens',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'vient',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'venons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'viennent',
    },
    'prendre': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'prends',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'prends',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'prend',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'prenons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'prennent',
    },
    'dire': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'dis',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'dis',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'dit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'disons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'disent',
    },
    'boire': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'bois',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'bois',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'boit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'buvons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'boivent',
    },
    'écrire': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'écris',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'écris',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'écrit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'écrivons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'écrivent',
    },
    'courir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'cours',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'cours',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'court',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'courons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'courent',
    },
    'dormir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'dors',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'dors',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'dort',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'dormons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'dorment',
    },
    'lire': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'lis',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'lis',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'lit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'lisons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'lisent',
    },
    'vivre': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'vis',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vis',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'vit',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vivons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'vivent',
    },
    'ouvrir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'ouvre',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'ouvres',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'ouvre',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'ouvrons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'ouvrent',
    },
    'aimer': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'aime',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'aimes',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'aime',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'aimons',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'aiment',
    },
}

# -- German irregular verbs --
_DE_IRREGULAR_VERBS = {
    'sein': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'bin',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'bist',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'ist',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'sind',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'sind',
    },
    'haben': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'habe',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'hast',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'hat',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'haben',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'haben',
    },
    'werden': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'werde',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'wirst',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'wird',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'werden',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'werden',
    },
    'wissen': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'weiss',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'weisst',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'weiss',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'wissen',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'wissen',
    },
    'wollen': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'will',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'willst',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'will',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'wollen',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'wollen',
    },
    'mögen': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'mag',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'magst',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'mag',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'mögen',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'mögen',
    },
}

# German stem-vowel changes: {lemma: (3s_form, 2s_form)}
_DE_STEM_CHANGERS = {
    # e -> i
    'essen': ('isst', 'isst'), 'geben': ('gibt', 'gibst'),
    'nehmen': ('nimmt', 'nimmst'), 'sprechen': ('spricht', 'sprichst'),
    'helfen': ('hilft', 'hilfst'), 'treffen': ('trifft', 'triffst'),
    'werfen': ('wirft', 'wirfst'), 'brechen': ('bricht', 'brichst'),
    # e -> ie
    'sehen': ('sieht', 'siehst'), 'lesen': ('liest', 'liest'),
    'empfehlen': ('empfiehlt', 'empfiehlst'),
    # a -> ä
    'schlafen': ('schläft', 'schläfst'), 'fahren': ('fährt', 'fährst'),
    'tragen': ('trägt', 'trägst'), 'schlagen': ('schlägt', 'schlägst'),
    'laufen': ('läuft', 'läufst'), 'fallen': ('fällt', 'fällst'),
}

# -- Portuguese irregular verbs --
_PT_IRREGULAR_VERBS = {
    'ser': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'sou',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'és',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'é',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'somos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'são',
    },
    'ir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'vou',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vais',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'vai',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vamos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'vão',
    },
    'ter': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'tenho',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'tens',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'tem',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'temos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'têm',
    },
    'fazer': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'faço',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'fazes',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'faz',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'fazemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'fazem',
    },
    'ver': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'vejo',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vês',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'vê',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'veem',
    },
    'vir': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'venho',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'vens',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'vem',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'vimos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'vêm',
    },
    'dizer': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'digo',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'dizes',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'diz',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'dizemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'dizem',
    },
    'dar': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'dou',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'dás',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'dá',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'damos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'dão',
    },
    'querer': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'quero',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'queres',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'quer',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'queremos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'querem',
    },
    'saber': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'sei',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'sabes',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'sabe',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'sabemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'sabem',
    },
    'ler': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'leio',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'lês',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'lê',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'lemos',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'leem',
    },
}

# -- English irregular verbs (only a few are truly irregular in present) --
_EN_IRREGULAR_VERBS = {
    'be': {
        (SubType.FIRST_PERSON, SubType.SINGULAR): 'am',
        (SubType.SECOND_PERSON, SubType.SINGULAR): 'are',
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'is',
        (SubType.FIRST_PERSON, SubType.PLURAL): 'are',
        (SubType.THIRD_PERSON, SubType.PLURAL): 'are',
    },
    'have': {
        (SubType.THIRD_PERSON, SubType.SINGULAR): 'has',
    },
}

_IRREGULAR_VERBS = {
    'spanish': _ES_IRREGULAR_VERBS,
    'french': _FR_IRREGULAR_VERBS,
    'german': _DE_IRREGULAR_VERBS,
    'portuguese': _PT_IRREGULAR_VERBS,
    'english': _EN_IRREGULAR_VERBS,
    'japanese': {},
}


# ============================================================================
# Adjective irregulars (only forms that suffix rules can't produce)
# ============================================================================

_FR_IRREGULAR_ADJS = {
    'beau': {'f_sg': 'belle', 'f_pl': 'belles', 'm_pl': 'beaux'},
    'vieux': {'f_sg': 'vieille', 'f_pl': 'vieilles', 'm_pl': 'vieux'},
    'nouveau': {'f_sg': 'nouvelle', 'f_pl': 'nouvelles', 'm_pl': 'nouveaux'},
    'blanc': {'f_sg': 'blanche', 'f_pl': 'blanches'},
    'bon': {'f_sg': 'bonne', 'f_pl': 'bonnes'},
    'faux': {'f_sg': 'fausse', 'f_pl': 'fausses', 'm_pl': 'faux'},
}

# German adjectives require strong/weak/mixed paradigms based on determiner.
# Too complex for suffix rules — keep a small manual table for demo coverage.
_DE_ADJ_FORMS = {
    'gross': {
        (SubType.MASCULINE, SubType.SINGULAR): 'grosse',
        (SubType.FEMININE, SubType.SINGULAR): 'grosse',
        (SubType.NEUTER, SubType.SINGULAR): 'grosses',
        (SubType.PLURAL,): 'grossen',
    },
    'klein': {
        (SubType.MASCULINE, SubType.SINGULAR): 'kleine',
        (SubType.FEMININE, SubType.SINGULAR): 'kleine',
        (SubType.NEUTER, SubType.SINGULAR): 'kleines',
    },
    'weiss': {
        (SubType.MASCULINE, SubType.SINGULAR): 'weisser',
        (SubType.FEMININE, SubType.SINGULAR): 'weisse',
        (SubType.NEUTER, SubType.SINGULAR): 'weisses',
    },
    'gut': {
        (SubType.MASCULINE, SubType.SINGULAR): 'guter',
        (SubType.FEMININE, SubType.SINGULAR): 'gute',
        (SubType.NEUTER, SubType.SINGULAR): 'gutes',
    },
}


# ============================================================================
# Noun gender: known exceptions + suffix heuristics
# ============================================================================

# Spanish exceptions to suffix heuristics
_ES_GENDER_EXCEPTIONS = {
    'mano': SubType.FEMININE, 'día': SubType.MASCULINE,
    'agua': SubType.FEMININE, 'mapa': SubType.MASCULINE,
    'problema': SubType.MASCULINE, 'sistema': SubType.MASCULINE,
    'tema': SubType.MASCULINE, 'programa': SubType.MASCULINE,
    'idioma': SubType.MASCULINE, 'clima': SubType.MASCULINE,
    'planeta': SubType.MASCULINE, 'poeta': SubType.MASCULINE,
    'foto': SubType.FEMININE, 'moto': SubType.FEMININE,
    'radio': SubType.FEMININE,
    # -e ending feminine nouns
    'madre': SubType.FEMININE, 'noche': SubType.FEMININE,
    'calle': SubType.FEMININE, 'clase': SubType.FEMININE,
    'sangre': SubType.FEMININE, 'llave': SubType.FEMININE,
    'muerte': SubType.FEMININE, 'gente': SubType.FEMININE,
    'mente': SubType.FEMININE, 'parte': SubType.FEMININE,
    # consonant-ending feminine nouns
    'flor': SubType.FEMININE, 'mujer': SubType.FEMININE,
    'ciudad': SubType.FEMININE, 'pared': SubType.FEMININE,
    'luz': SubType.FEMININE, 'sal': SubType.FEMININE,
    'voz': SubType.FEMININE, 'vez': SubType.FEMININE,
}

_PT_GENDER_EXCEPTIONS = {
    'mão': SubType.FEMININE, 'dia': SubType.MASCULINE,
    'água': SubType.FEMININE, 'mapa': SubType.MASCULINE,
    'problema': SubType.MASCULINE, 'sistema': SubType.MASCULINE,
    'tema': SubType.MASCULINE, 'programa': SubType.MASCULINE,
    'foto': SubType.FEMININE, 'moto': SubType.FEMININE,
    # -e ending feminine nouns
    'mãe': SubType.FEMININE, 'noite': SubType.FEMININE,
    'árvore': SubType.FEMININE, 'classe': SubType.FEMININE,
    'gente': SubType.FEMININE, 'parte': SubType.FEMININE,
    # consonant-ending feminine nouns
    'flor': SubType.FEMININE, 'mulher': SubType.FEMININE,
    'cor': SubType.FEMININE, 'luz': SubType.FEMININE,
    'voz': SubType.FEMININE, 'vez': SubType.FEMININE,
}

_FR_GENDER_EXCEPTIONS = {
    # Masculine words ending in -e (would wrongly default to MASCULINE anyway,
    # but explicit for clarity)
    'homme': SubType.MASCULINE, 'père': SubType.MASCULINE,
    'frère': SubType.MASCULINE, 'livre': SubType.MASCULINE,
    'arbre': SubType.MASCULINE, 'monde': SubType.MASCULINE,
    'musée': SubType.MASCULINE, 'lycée': SubType.MASCULINE,
    # Feminine words ending in -e (would wrongly default to MASCULINE)
    'mère': SubType.FEMININE, 'femme': SubType.FEMININE,
    'fille': SubType.FEMININE, 'famille': SubType.FEMININE,
    'personne': SubType.FEMININE, 'table': SubType.FEMININE,
    'chaise': SubType.FEMININE, 'étoile': SubType.FEMININE,
    'vie': SubType.FEMININE, 'ville': SubType.FEMININE,
    'école': SubType.FEMININE, 'porte': SubType.FEMININE,
    'fenêtre': SubType.FEMININE, 'chambre': SubType.FEMININE,
    'maison': SubType.FEMININE, 'lune': SubType.FEMININE,
    # Feminine with consonant ending
    'nuit': SubType.FEMININE, 'main': SubType.FEMININE,
    'fleur': SubType.FEMININE, 'soeur': SubType.FEMININE,
    'chair': SubType.FEMININE,
    # Masculine that suffix rules get right but worth being explicit
    'chien': SubType.MASCULINE, 'chat': SubType.MASCULINE,
    'soleil': SubType.MASCULINE, 'jour': SubType.MASCULINE,
    'parc': SubType.MASCULINE, 'nom': SubType.MASCULINE,
}

# German gender must be memorized — keep a curated table for common nouns.
_DE_NOUN_GENDERS = {
    'Hund': SubType.MASCULINE, 'Katze': SubType.FEMININE,
    'Vogel': SubType.MASCULINE, 'Maus': SubType.FEMININE,
    'Pferd': SubType.NEUTER, 'Fisch': SubType.MASCULINE,
    'Mann': SubType.MASCULINE, 'Frau': SubType.FEMININE,
    'Kind': SubType.NEUTER, 'Junge': SubType.MASCULINE,
    'Mädchen': SubType.NEUTER, 'Baby': SubType.NEUTER,
    'Mutter': SubType.FEMININE, 'Vater': SubType.MASCULINE,
    'Schwester': SubType.FEMININE, 'Bruder': SubType.MASCULINE,
    'Familie': SubType.FEMININE,
    'Person': SubType.FEMININE, 'Freund': SubType.MASCULINE,
    'Lehrer': SubType.MASCULINE, 'Student': SubType.MASCULINE,
    'Arzt': SubType.MASCULINE, 'König': SubType.MASCULINE,
    'Königin': SubType.FEMININE, 'Leute': SubType.PLURAL,
    'Hand': SubType.FEMININE, 'Kopf': SubType.MASCULINE,
    'Auge': SubType.NEUTER, 'Herz': SubType.NEUTER,
    'Haus': SubType.NEUTER, 'Zuhause': SubType.NEUTER,
    'Zimmer': SubType.NEUTER,
    'Tür': SubType.FEMININE, 'Fenster': SubType.NEUTER,
    'Schule': SubType.FEMININE, 'Stadt': SubType.FEMININE,
    'Park': SubType.MASCULINE, 'Auto': SubType.NEUTER,
    'Tisch': SubType.MASCULINE, 'Stuhl': SubType.MASCULINE,
    'Buch': SubType.NEUTER,
    'Baum': SubType.MASCULINE, 'Blume': SubType.FEMININE,
    'Sonne': SubType.FEMININE, 'Mond': SubType.MASCULINE,
    'Stern': SubType.MASCULINE, 'Wasser': SubType.NEUTER,
    'Essen': SubType.NEUTER, 'Tag': SubType.MASCULINE,
    'Nacht': SubType.FEMININE, 'Zeit': SubType.FEMININE,
    'Name': SubType.MASCULINE, 'Welt': SubType.FEMININE,
    'Leben': SubType.NEUTER, 'Geld': SubType.NEUTER,
    'Arbeit': SubType.FEMININE, 'Land': SubType.NEUTER,
    'Farbe': SubType.FEMININE,
}


# ============================================================================
# MorphologyEngine — the public API
# ============================================================================

class MorphologyEngine:
    """Rule-based morphological inflection with irregular overrides."""

    def __init__(self, language: str):
        self.language = language
        self._irregulars = _IRREGULAR_VERBS.get(language, {})

    def conjugate_verb(self, lemma: str, person: SubType,
                       number: SubType) -> str:
        """Conjugate a verb in present indicative."""
        key = (person, number)

        # 1. Check irregulars table
        if lemma in self._irregulars:
            forms = self._irregulars[lemma]
            if key in forms:
                return forms[key]
            return lemma

        # 2. Language-specific conjugation
        if self.language == 'spanish':
            return self._conjugate_spanish(lemma, person, number)
        if self.language == 'french':
            return self._conjugate_french(lemma, person, number)
        if self.language == 'german':
            return self._conjugate_german(lemma, person, number)
        if self.language == 'portuguese':
            return self._conjugate_portuguese(lemma, person, number)
        if self.language == 'english':
            return self._conjugate_english(lemma, person, number)

        # Japanese / unknown: no conjugation
        return lemma

    def inflect_adjective(self, lemma: str, gender: SubType = None,
                          number: SubType = SubType.SINGULAR) -> str:
        """Inflect an adjective for gender/number agreement."""
        if self.language in ('english', 'japanese'):
            return lemma

        if self.language == 'german':
            return self._inflect_adj_german(lemma, gender, number)
        if self.language == 'french':
            return self._inflect_adj_french(lemma, gender, number)
        if self.language in ('spanish', 'portuguese'):
            return self._inflect_adj_romance(lemma, gender, number)

        return lemma

    def detect_gender(self, noun_lemma: str) -> Optional[SubType]:
        """Detect grammatical gender from word form."""
        if self.language in ('english', 'japanese'):
            return None

        if self.language == 'german':
            return _DE_NOUN_GENDERS.get(noun_lemma, SubType.MASCULINE)

        if self.language == 'spanish':
            return self._detect_gender_spanish(noun_lemma)
        if self.language == 'portuguese':
            return self._detect_gender_portuguese(noun_lemma)
        if self.language == 'french':
            return self._detect_gender_french(noun_lemma)

        return SubType.MASCULINE

    # ------------------------------------------------------------------
    # Spanish verb conjugation
    # ------------------------------------------------------------------

    def _conjugate_spanish(self, lemma: str, person: SubType,
                           number: SubType) -> str:
        # Check stem-change 1s override (tengo, vengo, etc.)
        if (person == SubType.FIRST_PERSON and number == SubType.SINGULAR
                and lemma in _ES_STEM_CHANGE_1S):
            return _ES_STEM_CHANGE_1S[lemma]

        if len(lemma) < 3:
            return lemma

        ending = lemma[-2:]  # ar, er, ir
        stem = lemma[:-2]

        if ending not in ('ar', 'er', 'ir'):
            return lemma

        # Apply stem change for boot-pattern positions (1s, 2s, 3s, 3p)
        boot = (person != SubType.FIRST_PERSON or number != SubType.PLURAL)
        if lemma in _ES_STEM_CHANGERS and boot:
            from_v, to_v = _ES_STEM_CHANGERS[lemma]
            # Find last occurrence of the vowel to change in the stem
            idx = stem.rfind(from_v)
            if idx >= 0:
                stem = stem[:idx] + to_v + stem[idx + len(from_v):]

        # Regular suffix lookup
        suffixes = {
            'ar': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'as',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'a',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'amos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'an',
            },
            'er': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'e',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'emos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'en',
            },
            'ir': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'e',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'imos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'en',
            },
        }

        key = (person, number)
        if key in suffixes[ending]:
            # For 1p, use original stem (no stem change in boot pattern)
            if person == SubType.FIRST_PERSON and number == SubType.PLURAL:
                return lemma[:-2] + suffixes[ending][key]
            return stem + suffixes[ending][key]

        return lemma

    # ------------------------------------------------------------------
    # French verb conjugation
    # ------------------------------------------------------------------

    def _conjugate_french(self, lemma: str, person: SubType,
                          number: SubType) -> str:
        if len(lemma) < 3:
            return lemma

        key = (person, number)

        # Group 1: -er verbs (regular, covers ~90% of French verbs)
        if lemma.endswith('er'):
            stem = lemma[:-2]
            suffixes = {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'e',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'e',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'ons',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'ent',
            }
            if key in suffixes:
                return stem + suffixes[key]
            return lemma

        # Group 2: -ir verbs with -iss- infix (regular -ir)
        if lemma.endswith('ir'):
            stem = lemma[:-2]
            suffixes = {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'is',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'is',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'it',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'issons',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'issent',
            }
            if key in suffixes:
                return stem + suffixes[key]
            return lemma

        # Group 3: -re verbs
        if lemma.endswith('re'):
            stem = lemma[:-2]
            suffixes = {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 's',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 's',
                (SubType.THIRD_PERSON, SubType.SINGULAR): '',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'ons',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'ent',
            }
            if key in suffixes:
                return stem + suffixes[key]
            return lemma

        return lemma

    # ------------------------------------------------------------------
    # German verb conjugation
    # ------------------------------------------------------------------

    def _conjugate_german(self, lemma: str, person: SubType,
                          number: SubType) -> str:
        if not lemma.endswith('en') and not lemma.endswith('n'):
            return lemma

        stem = lemma[:-2] if lemma.endswith('en') else lemma[:-1]
        key = (person, number)

        # Check stem-vowel changes (only affect 2s and 3s)
        if lemma in _DE_STEM_CHANGERS:
            form_3s, form_2s = _DE_STEM_CHANGERS[lemma]
            if key == (SubType.THIRD_PERSON, SubType.SINGULAR):
                return form_3s
            if key == (SubType.SECOND_PERSON, SubType.SINGULAR):
                return form_2s

        # Stems ending in -t/-d need linking -e-
        needs_e = stem[-1] in ('t', 'd') if stem else False

        suffixes = {
            (SubType.FIRST_PERSON, SubType.SINGULAR): 'e',
            (SubType.SECOND_PERSON, SubType.SINGULAR): 'est' if needs_e else 'st',
            (SubType.THIRD_PERSON, SubType.SINGULAR): 'et' if needs_e else 't',
            (SubType.FIRST_PERSON, SubType.PLURAL): 'en',
            (SubType.THIRD_PERSON, SubType.PLURAL): 'en',
        }

        if key in suffixes:
            return stem + suffixes[key]

        return lemma

    # ------------------------------------------------------------------
    # Portuguese verb conjugation
    # ------------------------------------------------------------------

    def _conjugate_portuguese(self, lemma: str, person: SubType,
                              number: SubType) -> str:
        if len(lemma) < 3:
            return lemma

        ending = lemma[-2:]
        stem = lemma[:-2]

        if ending not in ('ar', 'er', 'ir'):
            return lemma

        suffixes = {
            'ar': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'as',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'a',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'amos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'am',
            },
            'er': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'e',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'emos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'em',
            },
            'ir': {
                (SubType.FIRST_PERSON, SubType.SINGULAR): 'o',
                (SubType.SECOND_PERSON, SubType.SINGULAR): 'es',
                (SubType.THIRD_PERSON, SubType.SINGULAR): 'e',
                (SubType.FIRST_PERSON, SubType.PLURAL): 'imos',
                (SubType.THIRD_PERSON, SubType.PLURAL): 'em',
            },
        }

        key = (person, number)
        if key in suffixes[ending]:
            return stem + suffixes[ending][key]

        return lemma

    # ------------------------------------------------------------------
    # English verb conjugation
    # ------------------------------------------------------------------

    def _conjugate_english(self, lemma: str, person: SubType,
                           number: SubType) -> str:
        # English only inflects in 3rd person singular present
        if person != SubType.THIRD_PERSON or number != SubType.SINGULAR:
            return lemma

        # Sibilant endings: +es
        if lemma.endswith(('s', 'sh', 'ch', 'x', 'z', 'o')):
            return lemma + 'es'

        # Consonant + y: -y + ies
        if lemma.endswith('y') and len(lemma) > 1 and lemma[-2] not in 'aeiou':
            return lemma[:-1] + 'ies'

        # Default: +s
        return lemma + 's'

    # ------------------------------------------------------------------
    # Adjective inflection
    # ------------------------------------------------------------------

    def _inflect_adj_romance(self, lemma: str, gender: SubType,
                             number: SubType) -> str:
        """Spanish / Portuguese adjective inflection via suffix rules."""
        is_fem = (gender == SubType.FEMININE)
        is_pl = (number == SubType.PLURAL)

        # Ends in -o: regular 4-form adjective
        if lemma.endswith('o'):
            base = lemma[:-1]
            if is_fem and is_pl:
                return base + 'as'
            if is_fem:
                return base + 'a'
            if is_pl:
                return base + 'os'
            return lemma

        # Ends in -e: invariant gender, +s for plural
        if lemma.endswith('e'):
            if is_pl:
                return lemma + 's'
            return lemma

        # Ends in -z: -ces for plural, invariant gender
        if lemma.endswith('z'):
            if is_pl:
                return lemma[:-1] + 'ces'
            return lemma

        # Ends in consonant (general): invariant gender, +es for plural
        if lemma and lemma[-1] not in 'aeiouáéíóú':
            if is_pl:
                return lemma + 'es'
            return lemma

        # Ends in -a (like "rosa"): invariant gender, +s for plural
        if lemma.endswith('a'):
            if is_pl:
                return lemma + 's'
            return lemma

        # Default
        if is_pl:
            return lemma + 's'
        return lemma

    def _inflect_adj_french(self, lemma: str, gender: SubType,
                            number: SubType) -> str:
        """French adjective inflection via suffix rules + irregulars."""
        is_fem = (gender == SubType.FEMININE)
        is_pl = (number == SubType.PLURAL)

        # Check irregulars first
        if lemma in _FR_IRREGULAR_ADJS:
            irr = _FR_IRREGULAR_ADJS[lemma]
            if is_fem and is_pl:
                return irr.get('f_pl', irr.get('f_sg', lemma) + 's')
            if is_fem:
                return irr.get('f_sg', lemma + 'e')
            if is_pl:
                return irr.get('m_pl', lemma + 's')
            return lemma

        # -eux -> -euse (feminine)
        if lemma.endswith('eux'):
            if is_fem:
                base = lemma[:-3] + 'euse'
                return base + 's' if is_pl else base
            return lemma if not is_pl else lemma

        # Already ends in -e: invariant for gender
        if lemma.endswith('e'):
            if is_pl:
                return lemma + 's'
            return lemma

        # Default French: feminine +e, plurals +s
        form = lemma
        if is_fem:
            form = lemma + 'e'
        if is_pl:
            form = form + 's'
        return form

    def _inflect_adj_german(self, lemma: str, gender: SubType,
                            number: SubType) -> str:
        """German adjective inflection — manual table lookup."""
        if lemma in _DE_ADJ_FORMS:
            forms = _DE_ADJ_FORMS[lemma]
            # Try (gender, number) then (number,)
            keys = []
            if gender and number:
                keys.append((gender, number))
            if number:
                keys.append((number,))
            for key in keys:
                if key in forms:
                    return forms[key]
        # Fallback: German predicative adjectives are uninflected
        return lemma

    # ------------------------------------------------------------------
    # Gender detection heuristics
    # ------------------------------------------------------------------

    def _detect_gender_spanish(self, noun: str) -> SubType:
        if noun in _ES_GENDER_EXCEPTIONS:
            return _ES_GENDER_EXCEPTIONS[noun]
        if noun.endswith('o'):
            return SubType.MASCULINE
        if noun.endswith('a'):
            return SubType.FEMININE
        if noun.endswith(('ción', 'sión', 'dad', 'tud', 'ez', 'triz')):
            return SubType.FEMININE
        if noun.endswith(('or', 'aje')):
            return SubType.MASCULINE
        return SubType.MASCULINE

    def _detect_gender_portuguese(self, noun: str) -> SubType:
        if noun in _PT_GENDER_EXCEPTIONS:
            return _PT_GENDER_EXCEPTIONS[noun]
        if noun.endswith('o'):
            return SubType.MASCULINE
        if noun.endswith('a'):
            return SubType.FEMININE
        if noun.endswith(('ção', 'são', 'dade', 'tude', 'ez')):
            return SubType.FEMININE
        if noun.endswith(('or', 'agem')):
            return SubType.MASCULINE
        return SubType.MASCULINE

    def _detect_gender_french(self, noun: str) -> SubType:
        if noun in _FR_GENDER_EXCEPTIONS:
            return _FR_GENDER_EXCEPTIONS[noun]
        if noun.endswith(('tion', 'sion', 'ure', 'ée', 'té', 'ette')):
            return SubType.FEMININE
        if noun.endswith(('ment', 'age', 'isme', 'eur')):
            return SubType.MASCULINE
        return SubType.MASCULINE
